#!/usr/bin/env bash
# Idempotent scratch layout for b20-mlip on the cluster; called by `b20mlip cluster bootstrap`
# right after the repo rsync (COMMANDS["remote_layout"]).  Usage: remote_bootstrap.sh <scratch>
#
# Creates <scratch>/b20-mlip/{jobs,bin,logs}, <scratch>/bin, <scratch>/.uv-cache and writes
# <scratch>/b20-mlip/env.sh, which sbatch scripts may `source` to get B20_SCRATCH, B20_REPO,
# the uv/micromamba cache locations (home directories are 10 GB on Tillicum) and PATH.
set -euo pipefail
scratch="${1:?usage: remote_bootstrap.sh <scratch>}"
scratch="${scratch%/}"
repo="$scratch/b20-mlip"
mkdir -p "$repo/jobs" "$repo/bin" "$repo/logs" "$scratch/bin" "$scratch/.uv-cache" "$scratch/.uv-python"
cat > "$repo/env.sh" <<EOF
# generated by scripts/tillicum/remote_bootstrap.sh — source me in sbatch scripts
export B20_SCRATCH="$scratch"
export B20_REPO="$repo"
export UV_CACHE_DIR="$scratch/.uv-cache"
export UV_PYTHON_INSTALL_DIR="$scratch/.uv-python"
export MAMBA_ROOT_PREFIX="$scratch/.micromamba"
export PATH="$repo/bin:$scratch/bin:\$HOME/.local/bin:\$PATH"
EOF
echo "layout ok: $repo (env: $repo/env.sh)"
